import crypto from 'crypto';
import bcrypt from 'bcryptjs';
import { connectDB } from './db';
import ComplaintModel from '@/models/Complaint';
import UserModel from '@/models/User';
import SettingsModel from '@/models/Settings';
import DigestModel from '@/models/Digest';
import { IComplaint, IUser, ISettings } from '@/types';

// Helper timestamp functions
function hoursAgo(h: number): string {
  const d = new Date();
  d.setTime(d.getTime() - h * 60 * 60 * 1000);
  return d.toISOString();
}

function daysAgo(days: number, hoursOffset = 0): string {
  const d = new Date();
  d.setDate(d.getDate() - days);
  d.setHours(d.getHours() - hoursOffset);
  return d.toISOString();
}

export async function runDatabaseSeed() {
  console.log('🌱 Starting SocietyPulse Database Seed with ~30 Realistic Complaints...');
  await connectDB();

  // 1. Seed Committee Users (passwords must come from env or be randomly generated per Section 8)
  const isEnvAdminPass = Boolean(process.env.SEED_ADMIN_PASSWORD);
  const isEnvMemberPass = Boolean(process.env.SEED_MEMBER_PASSWORD);

  const adminPassword = process.env.SEED_ADMIN_PASSWORD || crypto.randomBytes(8).toString('hex');
  const memberPassword = process.env.SEED_MEMBER_PASSWORD || crypto.randomBytes(8).toString('hex');

  console.log('\n🔐 COMMITTEE CREDENTIALS (Generated for this environment):');
  if (!isEnvAdminPass) {
    console.log(`   Admin (admin@society.org): ${adminPassword} [generated randomly, set SEED_ADMIN_PASSWORD to override]`);
  } else {
    console.log('   Admin (admin@society.org): [configured via SEED_ADMIN_PASSWORD]');
  }
  if (!isEnvMemberPass) {
    console.log(`   Member (secretary@society.org): ${memberPassword} [generated randomly, set SEED_MEMBER_PASSWORD to override]\n`);
  } else {
    console.log('   Member (secretary@society.org): [configured via SEED_MEMBER_PASSWORD]\n');
  }

  const passwordHashAdmin = await bcrypt.hash(adminPassword, 10);
  const passwordHashMember = await bcrypt.hash(memberPassword, 10);

  const users: IUser[] = [
    {
      name: 'Vikram Malhotra',
      email: 'admin@society.org',
      passwordHash: passwordHashAdmin,
      role: 'admin',
      phone: '+91 98201 23456',
      createdAt: daysAgo(30),
    },
    {
      name: 'Ananya Deshmukh',
      email: 'secretary@society.org',
      passwordHash: passwordHashMember,
      role: 'member',
      phone: '+91 98202 34567',
      createdAt: daysAgo(30),
    },
    {
      name: 'Rajesh Nair',
      email: 'treasurer@society.org',
      passwordHash: passwordHashMember,
      role: 'member',
      phone: '+91 98203 45678',
      createdAt: daysAgo(30),
    },
  ];

  // 2. Default Society Settings with editable Helplines
  const sampleSettings: ISettings = {
    societyName: 'Greenwood Palms Co-op Housing Society',
    totalFlats: 120,
    wings: ['A', 'B', 'C'],
    categories: ['water', 'lift', 'parking', 'noise', 'cleaning', 'electrical', 'security', 'other'],
    slaHours: {
      critical: 2,
      high: 6,
      medium: 24,
      low: 72,
    },
    helpline: [
      { name: 'Security Main Gate', role: 'Security Desk', phone: '+91 00000 00000' },
      { name: 'Lift AMC Supervisor', role: 'Emergency Escalation', phone: '+91 00000 00000' },
      { name: 'Electrician Helpdesk', role: 'Electrical Services', phone: '+91 00000 00000' },
    ],
  };

  // 3. Realistic ~30 Complaints with isDemo: true, recurring Lift B issues (4x), 3 duplicate clusters, 10 resolved, 2 reopened
  const complaints: IComplaint[] = [
    // ----------------- OPEN CRITICAL (1 SAFETY ISSUE) -----------------
    {
      complaintId: 'SP-2026-0001',
      originalText: 'Active electrical sparks and smoke coming from meter box next to main staircase, Wing B! Urgent dhua nikal raha hai.',
      translatedText: 'Active electrical sparks and smoke reported from Wing B main staircase meter box.',
      language: 'hinglish',
      summary: 'Electrical sparking and smoke in Wing B meter room',
      category: 'electrical',
      urgency: 'critical',
      urgencyScore: 98,
      urgencyReason: 'Active electrical sparking and smoke poses immediate fire hazard',
      isSafetyRisk: true,
      status: 'in_progress',
      wing: 'B',
      flatNumber: 'B-102',
      commonArea: 'Ground Floor Meter Room',
      residentName: 'Arjun Mehta',
      phone: '+91 98205 11223',
      photoUrl: '',
      duplicateOf: null,
      reportCount: 1,
      assignedTo: 'Society Electrician Desk',
      needsManualTriage: false,
      aiOverridden: false,
      slaDueAt: hoursAgo(-1),
      isDemo: true,
      timeline: [
        { status: 'new', note: 'Resident reported sparking meter box', by: 'Arjun Mehta', at: hoursAgo(1.5) },
        { status: 'triaged', note: 'AI marked Critical fire risk (98)', by: 'AI Triage', at: hoursAgo(1.4) },
        { status: 'in_progress', note: 'Main breaker tripped by security guard. Electrician dispatched.', by: 'Vikram Malhotra', at: hoursAgo(0.8) },
      ],
      internalNotes: [{ note: 'BSES emergency notified. Fire extinguishers placed on standby.', author: 'Vikram Malhotra', createdAt: hoursAgo(0.7) }],
      createdAt: hoursAgo(1.5),
      updatedAt: hoursAgo(0.8),
    },

    // ----------------- OPEN HIGH ISSUES (3 ISSUES) -----------------
    // RECURRING LIFT B ISSUE - FAILURE #4 (Current)
    {
      complaintId: 'SP-2026-0002',
      originalText: 'Lift B is stuck on 4th floor again! The motor is making grinding noise and doors will not open.',
      translatedText: 'Lift B motor failure and stuck doors on 4th floor.',
      language: 'en',
      summary: 'Wing B passenger elevator motor breakdown on 4th floor',
      category: 'lift',
      urgency: 'high',
      urgencyScore: 84,
      urgencyReason: 'Primary elevator outage in multi-storey wing',
      isSafetyRisk: false,
      status: 'assigned',
      wing: 'B',
      flatNumber: 'B-403',
      commonArea: 'Lift B Shaft',
      residentName: 'Priya Chawla',
      phone: '+91 98205 22334',
      photoUrl: '',
      duplicateOf: null,
      reportCount: 3, // DUPLICATE GROUP 1 PARENT (3 reports)
      assignedTo: 'Otis Elevator AMC',
      needsManualTriage: false,
      aiOverridden: false,
      slaDueAt: hoursAgo(-3),
      isDemo: true,
      timeline: [
        { status: 'new', note: 'Resident reported Lift B breakdown', by: 'Priya Chawla', at: hoursAgo(3.8) },
        { status: 'triaged', note: 'AI classified as High Priority elevator breakdown', by: 'AI Triage', at: hoursAgo(3.7) },
        { status: 'assigned', note: 'Escalated to Otis AMC emergency technician ticket #OT-8891', by: 'Ananya Deshmukh', at: hoursAgo(2.5) },
      ],
      internalNotes: [{ note: 'This is the 4th failure of Lift B this month. Need to withhold AMC payment pending thorough motor overhaul.', author: 'Rajesh Nair', createdAt: hoursAgo(2.0) }],
      createdAt: hoursAgo(3.8),
      updatedAt: hoursAgo(2.5),
    },
    // DUPLICATE GROUP 1 CHILD
    {
      complaintId: 'SP-2026-0003',
      originalText: 'लिफ्ट बी बंद है 4th फ्लोर पर, कृपया जल्दी ठीक करवाएं।',
      translatedText: 'Lift B is shut on 4th floor, please fix promptly.',
      language: 'hi',
      summary: 'Lift B stoppage on 4th floor',
      category: 'lift',
      urgency: 'high',
      urgencyScore: 80,
      urgencyReason: 'Matches active elevator incident SP-2026-0002',
      isSafetyRisk: false,
      status: 'triaged',
      wing: 'B',
      flatNumber: 'B-601',
      commonArea: 'Lift B',
      residentName: 'Suresh Trivedi',
      phone: '+91 98205 33445',
      photoUrl: '',
      duplicateOf: 'SP-2026-0002',
      reportCount: 1,
      assignedTo: 'Otis Elevator AMC',
      needsManualTriage: false,
      aiOverridden: false,
      slaDueAt: hoursAgo(-3),
      isDemo: true,
      timeline: [
        { status: 'new', note: 'Resident submitted duplicate report in Hindi', by: 'Suresh Trivedi', at: hoursAgo(3.2) },
        { status: 'triaged', note: 'AI auto-linked duplicate to parent SP-2026-0002', by: 'AI Triage', at: hoursAgo(3.1) },
      ],
      internalNotes: [],
      createdAt: hoursAgo(3.2),
      updatedAt: hoursAgo(3.1),
    },

    // HIGH ISSUE 2 - WING A WATER OUTAGE (DUPLICATE GROUP 2 PARENT: 4 reports)
    {
      complaintId: 'SP-2026-0004',
      originalText: 'A wing me subah se bilkul pani nahi aa raha. All taps completely dry in entire line.',
      translatedText: 'Complete water outage in Wing A since morning.',
      language: 'hinglish',
      summary: 'Domestic water supply outage across Wing A',
      category: 'water',
      urgency: 'high',
      urgencyScore: 82,
      urgencyReason: 'Multi-flat water supply interruption',
      isSafetyRisk: false,
      status: 'in_progress',
      wing: 'A',
      flatNumber: 'A-302',
      commonArea: 'Wing A Riser Lines',
      residentName: 'Kavita Joshi',
      phone: '+91 98205 44556',
      photoUrl: '',
      duplicateOf: null,
      reportCount: 4,
      assignedTo: 'Plumbing Service Desk',
      needsManualTriage: false,
      aiOverridden: false,
      slaDueAt: hoursAgo(-2),
      isDemo: true,
      timeline: [
        { status: 'new', note: 'Reported water outage', by: 'Kavita Joshi', at: hoursAgo(5.2) },
        { status: 'triaged', note: 'AI marked High Priority domestic water loss', by: 'AI Triage', at: hoursAgo(5.1) },
        { status: 'in_progress', note: 'Plumber inspecting terrace booster pump', by: 'Vikram Malhotra', at: hoursAgo(3.0) },
      ],
      internalNotes: [{ note: 'Overhead sensor faulty, manual valve opened.', author: 'Vikram Malhotra', createdAt: hoursAgo(2.5) }],
      createdAt: hoursAgo(5.2),
      updatedAt: hoursAgo(3.0),
    },
    // DUPLICATE GROUP 2 CHILD 1
    {
      complaintId: 'SP-2026-0005',
      originalText: 'pani 2 din se nahi aa raha, flat A-404',
      translatedText: 'No water supply for 2 days in flat A-404.',
      language: 'hinglish',
      summary: 'Water shortage in Flat A-404',
      category: 'water',
      urgency: 'high',
      urgencyScore: 78,
      urgencyReason: 'Matches active water incident SP-2026-0004',
      isSafetyRisk: false,
      status: 'triaged',
      wing: 'A',
      flatNumber: 'A-404',
      commonArea: 'Wing A',
      residentName: 'Rohan Sen',
      phone: '+91 98205 55667',
      photoUrl: '',
      duplicateOf: 'SP-2026-0004',
      reportCount: 1,
      assignedTo: 'Plumbing Service Desk',
      needsManualTriage: false,
      aiOverridden: false,
      slaDueAt: hoursAgo(-2),
      isDemo: true,
      timeline: [
        { status: 'new', note: 'Duplicate report submitted', by: 'Rohan Sen', at: hoursAgo(4.5) },
        { status: 'triaged', note: 'AI merged into SP-2026-0004', by: 'AI Triage', at: hoursAgo(4.4) },
      ],
      internalNotes: [],
      createdAt: hoursAgo(4.5),
      updatedAt: hoursAgo(4.4),
    },
    // DUPLICATE GROUP 2 CHILD 2
    {
      complaintId: 'SP-2026-0006',
      originalText: 'हमारे फ्लैट A-101 में सुबह से पानी नहीं है।',
      translatedText: 'No water in flat A-101 since this morning.',
      language: 'hi',
      summary: 'Water shortage in Flat A-101',
      category: 'water',
      urgency: 'high',
      urgencyScore: 78,
      urgencyReason: 'Matches active water incident SP-2026-0004',
      isSafetyRisk: false,
      status: 'triaged',
      wing: 'A',
      flatNumber: 'A-101',
      commonArea: 'Wing A',
      residentName: 'Dinesh Gupta',
      phone: '+91 98205 66778',
      photoUrl: '',
      duplicateOf: 'SP-2026-0004',
      reportCount: 1,
      assignedTo: 'Plumbing Service Desk',
      needsManualTriage: false,
      aiOverridden: false,
      slaDueAt: hoursAgo(-2),
      isDemo: true,
      timeline: [
        { status: 'new', note: 'Reported in Hindi', by: 'Dinesh Gupta', at: hoursAgo(4.1) },
        { status: 'triaged', note: 'AI merged into SP-2026-0004', by: 'AI Triage', at: hoursAgo(4.0) },
      ],
      internalNotes: [],
      createdAt: hoursAgo(4.1),
      updatedAt: hoursAgo(4.0),
    },

    // HIGH ISSUE 3 - SECURITY GATE MOTOR
    {
      complaintId: 'SP-2026-0007',
      originalText: 'Main entrance security boom barrier motor burnt out. Gate is stuck open, unknown vehicles entering freely.',
      translatedText: 'Main security boom barrier failure allows unauthorized vehicle entry.',
      language: 'en',
      summary: 'Main entrance security boom barrier malfunction',
      category: 'security',
      urgency: 'high',
      urgencyScore: 79,
      urgencyReason: 'Compromised society perimeter security',
      isSafetyRisk: false,
      status: 'new',
      wing: 'C',
      flatNumber: 'Gate 1',
      commonArea: 'Main Security Gate',
      residentName: 'Sanjay Hegde',
      phone: '+91 98205 77889',
      photoUrl: '',
      duplicateOf: null,
      reportCount: 1,
      assignedTo: null,
      needsManualTriage: false,
      aiOverridden: false,
      slaDueAt: hoursAgo(-5),
      isDemo: true,
      timeline: [
        { status: 'new', note: 'Reported security barrier defect', by: 'Sanjay Hegde', at: hoursAgo(2.1) },
        { status: 'triaged', note: 'AI prioritized as High Security risk', by: 'AI Triage', at: hoursAgo(2.0) },
      ],
      internalNotes: [],
      createdAt: hoursAgo(2.1),
      updatedAt: hoursAgo(2.0),
    },

    // ----------------- MEDIUM & LOW ACTIVE ISSUES -----------------
    // DUPLICATE GROUP 3 PARENT (Parking blocked)
    {
      complaintId: 'SP-2026-0008',
      originalText: 'parking me kisi ne gaadi khadi kar di hai, meri gaadi nahi nikal rahi. Slot C-14 blocked.',
      translatedText: 'Unauthorized vehicle blocking parking slot C-14.',
      language: 'hinglish',
      summary: 'Unauthorized car parked blocking slot C-14',
      category: 'parking',
      urgency: 'medium',
      urgencyScore: 56,
      urgencyReason: 'Resident convenience and parking bay obstruction',
      isSafetyRisk: false,
      status: 'assigned',
      wing: 'C',
      flatNumber: 'C-204',
      commonArea: 'Basement Parking Slot C-14',
      residentName: 'Kunal Kapoor',
      phone: '+91 98205 88990',
      photoUrl: '',
      duplicateOf: null,
      reportCount: 2,
      assignedTo: 'Security Guard Desk',
      needsManualTriage: false,
      aiOverridden: false,
      slaDueAt: hoursAgo(-18),
      isDemo: true,
      timeline: [
        { status: 'new', note: 'Parking block reported', by: 'Kunal Kapoor', at: hoursAgo(6.5) },
        { status: 'assigned', note: 'Assigned to security to trace vehicle owner', by: 'Ananya Deshmukh', at: hoursAgo(5.0) },
      ],
      internalNotes: [{ note: 'White Swift MH02-EX-4491 traced to guest of C-502.', author: 'Ananya Deshmukh', createdAt: hoursAgo(4.8) }],
      createdAt: hoursAgo(6.5),
      updatedAt: hoursAgo(5.0),
    },
    // DUPLICATE GROUP 3 CHILD
    {
      complaintId: 'SP-2026-0009',
      originalText: 'Basement parking lane blocked by visitor Swift.',
      translatedText: 'Basement lane blocked by visitor vehicle.',
      language: 'en',
      summary: 'Visitor vehicle obstructing parking lane',
      category: 'parking',
      urgency: 'medium',
      urgencyScore: 50,
      urgencyReason: 'Duplicate parking obstruction report',
      isSafetyRisk: false,
      status: 'triaged',
      wing: 'C',
      flatNumber: 'C-301',
      commonArea: 'Basement Parking',
      residentName: 'Manoj Patel',
      phone: '+91 98205 99001',
      photoUrl: '',
      duplicateOf: 'SP-2026-0008',
      reportCount: 1,
      assignedTo: 'Security Guard Desk',
      needsManualTriage: false,
      aiOverridden: false,
      slaDueAt: hoursAgo(-18),
      isDemo: true,
      timeline: [
        { status: 'new', note: 'Reported parking issue', by: 'Manoj Patel', at: hoursAgo(6.0) },
        { status: 'triaged', note: 'AI linked to SP-2026-0008', by: 'AI Triage', at: hoursAgo(5.9) },
      ],
      internalNotes: [],
      createdAt: hoursAgo(6.0),
      updatedAt: hoursAgo(5.9),
    },

    // NOISE ISSUE
    {
      complaintId: 'SP-2026-0010',
      originalText: 'Music bahut loud hai raat ko 1 baje tak, C-101. Heavy bass vibrating floor.',
      translatedText: 'Loud music and heavy bass disturbance late at night in Flat C-101.',
      language: 'hinglish',
      summary: 'Late night loud music disturbance from Flat C-101',
      category: 'noise',
      urgency: 'medium',
      urgencyScore: 52,
      urgencyReason: 'Violation of residential quiet hours',
      isSafetyRisk: false,
      status: 'assigned',
      wing: 'C',
      flatNumber: 'C-101',
      commonArea: 'Wing C 1st Floor',
      residentName: 'Neelam Sen',
      phone: '+91 98206 11223',
      photoUrl: '',
      duplicateOf: null,
      reportCount: 1,
      assignedTo: 'Ananya Deshmukh',
      needsManualTriage: false,
      aiOverridden: false,
      slaDueAt: hoursAgo(-16),
      isDemo: true,
      timeline: [
        { status: 'new', note: 'Noise complaint submitted', by: 'Neelam Sen', at: hoursAgo(8.0) },
        { status: 'assigned', note: 'Secretary contacted tenant of C-101', by: 'Ananya Deshmukh', at: hoursAgo(7.5) },
      ],
      internalNotes: [{ note: 'First warning issued to tenant as per bye-laws.', author: 'Ananya Deshmukh', createdAt: hoursAgo(7.4) }],
      createdAt: hoursAgo(8.0),
      updatedAt: hoursAgo(7.5),
    },

    // CLEANING ISSUE
    {
      complaintId: 'SP-2026-0011',
      originalText: 'कॉरिडोर में कचरा 2 दिन से नहीं उठाया गया है। बहुत बदबू आ रही है।',
      translatedText: 'Corridor garbage not cleared for 2 days, causing foul smell.',
      language: 'hi',
      summary: 'Uncleared trash in 3rd floor corridor causing foul odor',
      category: 'cleaning',
      urgency: 'medium',
      urgencyScore: 48,
      urgencyReason: 'Sanitation and hygiene concern in common corridor',
      isSafetyRisk: false,
      status: 'new',
      wing: 'B',
      flatNumber: 'B-304',
      commonArea: '3rd Floor Corridor',
      residentName: 'Harish Nair',
      phone: '+91 98206 22334',
      photoUrl: '',
      duplicateOf: null,
      reportCount: 1,
      assignedTo: null,
      needsManualTriage: false,
      aiOverridden: false,
      slaDueAt: hoursAgo(-20),
      isDemo: true,
      timeline: [
        { status: 'new', note: 'Reported garbage issue in Hindi', by: 'Harish Nair', at: hoursAgo(4.0) },
        { status: 'triaged', note: 'AI categorized under Cleaning', by: 'AI Triage', at: hoursAgo(3.9) },
      ],
      internalNotes: [],
      createdAt: hoursAgo(4.0),
      updatedAt: hoursAgo(3.9),
    },

    // OTHER CATEGORY ISSUE
    {
      complaintId: 'SP-2026-0012',
      originalText: 'Children park slide has loose bolt and rusted handle at bottom landing.',
      translatedText: 'Children playground slide has loose fastener and rust.',
      language: 'en',
      summary: 'Playground slide loose bolt and rusted handle',
      category: 'other',
      urgency: 'low',
      urgencyScore: 34,
      urgencyReason: 'Routine playground equipment maintenance',
      isSafetyRisk: false,
      status: 'new',
      wing: 'A',
      flatNumber: 'Garden',
      commonArea: "Children's Play Area",
      residentName: 'Deepa Rao',
      phone: '+91 98206 33445',
      photoUrl: '',
      duplicateOf: null,
      reportCount: 1,
      assignedTo: null,
      needsManualTriage: false,
      aiOverridden: false,
      slaDueAt: hoursAgo(-48),
      isDemo: true,
      timeline: [
        { status: 'new', note: 'Playground issue reported', by: 'Deepa Rao', at: hoursAgo(12.0) },
        { status: 'triaged', note: 'AI categorized under Other (Routine)', by: 'AI Triage', at: hoursAgo(11.9) },
      ],
      internalNotes: [],
      createdAt: hoursAgo(12.0),
      updatedAt: hoursAgo(11.9),
    },

    // ----------------- REOPENED COMPLAINTS (2 CASES) -----------------
    {
      complaintId: 'SP-2026-0013',
      originalText: 'Basement storm water drain overflowed again after light rain. Smell is unbearable.',
      translatedText: 'Basement stormwater drain backflow recurring after rainfall.',
      language: 'en',
      summary: 'Recurring basement storm water drain overflow',
      category: 'water',
      urgency: 'high',
      urgencyScore: 76,
      urgencyReason: 'Reopened issue with unaddressed drain choke',
      isSafetyRisk: false,
      status: 'reopened',
      wing: 'B',
      flatNumber: 'Basement B',
      commonArea: 'Basement Pump Sump',
      residentName: 'Gaurav Singhal',
      phone: '+91 98206 44556',
      photoUrl: '',
      duplicateOf: null,
      reportCount: 1,
      assignedTo: 'Plumbing Service Desk',
      needsManualTriage: true,
      aiOverridden: false,
      slaDueAt: hoursAgo(-4),
      residentConfirmed: false,
      satisfactionRating: 2,
      isDemo: true,
      timeline: [
        { status: 'new', note: 'Initial drain choke reported', by: 'Gaurav Singhal', at: daysAgo(4) },
        { status: 'resolved', note: 'Technician cleared surface grates', by: 'Plumber', at: daysAgo(3) },
        { status: 'reopened', note: 'Resident rejected resolution: sump pump float switch failing', by: 'Gaurav Singhal', at: hoursAgo(6) },
      ],
      internalNotes: [{ note: 'Float switch needs replacement. Electrician also required.', author: 'Vikram Malhotra', createdAt: hoursAgo(5.5) }],
      createdAt: daysAgo(4),
      updatedAt: hoursAgo(6),
    },
    {
      complaintId: 'SP-2026-0014',
      originalText: 'Flat C-302 intercom loud static noise has started again. Cannot hear visitor voice.',
      translatedText: 'Intercom buzzing noise recurred in flat C-302.',
      language: 'en',
      summary: 'Recurring intercom static and audio distortion in C-302',
      category: 'other',
      urgency: 'medium',
      urgencyScore: 45,
      urgencyReason: 'Reopened telecommunication issue',
      isSafetyRisk: false,
      status: 'reopened',
      wing: 'C',
      flatNumber: 'C-302',
      commonArea: 'Wing C Intercom Riser',
      residentName: 'Tanvi Shinde',
      phone: '+91 98206 55667',
      photoUrl: '',
      duplicateOf: null,
      reportCount: 1,
      assignedTo: 'Intercom Vendor (Matrix)',
      needsManualTriage: false,
      aiOverridden: false,
      slaDueAt: hoursAgo(-12),
      residentConfirmed: false,
      satisfactionRating: 2,
      isDemo: true,
      timeline: [
        { status: 'new', note: 'Intercom static reported', by: 'Tanvi Shinde', at: daysAgo(5) },
        { status: 'resolved', note: 'Wire reseated in junction box', by: 'Vendor', at: daysAgo(4) },
        { status: 'reopened', note: 'Static noise recurred today', by: 'Tanvi Shinde', at: hoursAgo(10) },
      ],
      internalNotes: [],
      createdAt: daysAgo(5),
      updatedAt: hoursAgo(10),
    },

    // ----------------- RESOLVED COMPLAINTS (~10 REALISTIC CASES) -----------------
    // RECURRING LIFT B ISSUE - FAILURE #1 (24 days ago)
    {
      complaintId: 'SP-2026-0015',
      originalText: 'Lift B door alignment jammed on 2nd floor.',
      translatedText: 'Lift B door alignment jammed on 2nd floor.',
      language: 'en',
      summary: 'Wing B elevator door jam on 2nd floor',
      category: 'lift',
      urgency: 'high',
      urgencyScore: 75,
      urgencyReason: 'Elevator door jam',
      isSafetyRisk: false,
      status: 'resolved',
      wing: 'B',
      flatNumber: 'B-201',
      commonArea: 'Lift B',
      residentName: 'Priya Chawla',
      phone: '+91 98205 22334',
      photoUrl: '',
      duplicateOf: null,
      reportCount: 1,
      assignedTo: 'Otis Elevator AMC',
      needsManualTriage: false,
      aiOverridden: false,
      slaDueAt: daysAgo(24, -4),
      resolvedAt: daysAgo(24, -3),
      residentConfirmed: true,
      satisfactionRating: 5,
      isDemo: true,
      timeline: [
        { status: 'new', note: 'Door jam reported', by: 'Priya Chawla', at: daysAgo(24, 6) },
        { status: 'resolved', note: 'Door track lubricated and sensor adjusted', by: 'Otis Tech', at: daysAgo(24, 3) },
      ],
      internalNotes: [],
      createdAt: daysAgo(24, 6),
      updatedAt: daysAgo(24, 3),
    },

    // RECURRING LIFT B ISSUE - FAILURE #2 (16 days ago)
    {
      complaintId: 'SP-2026-0016',
      originalText: 'Lift B skipping 5th floor landing, stops roughly with jerk.',
      translatedText: 'Lift B floor landing sensor error on 5th floor.',
      language: 'en',
      summary: 'Wing B elevator 5th floor landing sensor error',
      category: 'lift',
      urgency: 'high',
      urgencyScore: 78,
      urgencyReason: 'Elevator levelling issue',
      isSafetyRisk: false,
      status: 'resolved',
      wing: 'B',
      flatNumber: 'B-504',
      commonArea: 'Lift B',
      residentName: 'Amit Saxena',
      phone: '+91 98206 66778',
      photoUrl: '',
      duplicateOf: null,
      reportCount: 2,
      assignedTo: 'Otis Elevator AMC',
      needsManualTriage: false,
      aiOverridden: false,
      slaDueAt: daysAgo(16, -4),
      resolvedAt: daysAgo(16, -2),
      residentConfirmed: true,
      satisfactionRating: 4,
      isDemo: true,
      timeline: [
        { status: 'new', note: 'Landing jerk reported', by: 'Amit Saxena', at: daysAgo(16, 8) },
        { status: 'resolved', note: 'Encoder calibrated and brake shoe adjusted', by: 'Otis AMC', at: daysAgo(16, 2) },
      ],
      internalNotes: [],
      createdAt: daysAgo(16, 8),
      updatedAt: daysAgo(16, 2),
    },

    // RECURRING LIFT B ISSUE - FAILURE #3 (7 days ago)
    {
      complaintId: 'SP-2026-0017',
      originalText: 'Lift B emergency brake tripped during evening peak hour.',
      translatedText: 'Lift B emergency brake trip during peak hours.',
      language: 'en',
      summary: 'Wing B elevator emergency brake lockup',
      category: 'lift',
      urgency: 'high',
      urgencyScore: 82,
      urgencyReason: 'Elevator brake safety lock',
      isSafetyRisk: false,
      status: 'resolved',
      wing: 'B',
      flatNumber: 'B-302',
      commonArea: 'Lift B Shaft',
      residentName: 'Sanjay Varma',
      phone: '+91 98206 77889',
      photoUrl: '',
      duplicateOf: null,
      reportCount: 2,
      assignedTo: 'Otis Elevator AMC',
      needsManualTriage: false,
      aiOverridden: false,
      slaDueAt: daysAgo(7, -4),
      resolvedAt: daysAgo(7, -3),
      residentConfirmed: true,
      satisfactionRating: 4,
      isDemo: true,
      timeline: [
        { status: 'new', note: 'Emergency brake trip reported', by: 'Sanjay Varma', at: daysAgo(7, 5) },
        { status: 'resolved', note: 'Controller reset and safety switch replaced', by: 'Otis Supervisor', at: daysAgo(7, 3) },
      ],
      internalNotes: [{ note: 'Warned Otis engineer about frequent breakdowns.', author: 'Vikram Malhotra', createdAt: daysAgo(7, 2) }],
      createdAt: daysAgo(7, 5),
      updatedAt: daysAgo(7, 3),
    },

    // RESOLVED WATER ISSUE (12 days ago)
    {
      complaintId: 'SP-2026-0018',
      originalText: 'Flushing line leak near shaft A-202 causing continuous water dripping into basement.',
      translatedText: 'Shaft water leak causing drainage into basement.',
      language: 'en',
      summary: 'Flushing line pipe leak near Wing A shaft',
      category: 'water',
      urgency: 'medium',
      urgencyScore: 60,
      urgencyReason: 'Active internal pipeline leakage',
      isSafetyRisk: false,
      status: 'resolved',
      wing: 'A',
      flatNumber: 'A-202',
      commonArea: 'Plumbing Shaft A',
      residentName: 'Naveen Jindal',
      phone: '+91 98206 88990',
      photoUrl: '',
      duplicateOf: null,
      reportCount: 1,
      assignedTo: 'Society Plumber (Ramesh)',
      needsManualTriage: false,
      aiOverridden: false,
      slaDueAt: daysAgo(12, -12),
      resolvedAt: daysAgo(12, -8),
      residentConfirmed: true,
      satisfactionRating: 5,
      isDemo: true,
      timeline: [
        { status: 'new', note: 'Shaft leak reported', by: 'Naveen Jindal', at: daysAgo(12, 14) },
        { status: 'resolved', note: 'Coupling clamp replaced by Ramesh', by: 'Ramesh Plumber', at: daysAgo(12, 8) },
      ],
      internalNotes: [],
      createdAt: daysAgo(12, 14),
      updatedAt: daysAgo(12, 8),
    },

    // RESOLVED ELECTRICAL ISSUE (18 days ago)
    {
      complaintId: 'SP-2026-0019',
      originalText: 'Wing C corridor lighting circuit breaker tripping every 10 minutes.',
      translatedText: 'Corridor lighting breaker repeatedly tripping in Wing C.',
      language: 'en',
      summary: 'Wing C 2nd floor lighting circuit tripping',
      category: 'electrical',
      urgency: 'medium',
      urgencyScore: 55,
      urgencyReason: 'Lighting circuit breaker short',
      isSafetyRisk: false,
      status: 'resolved',
      wing: 'C',
      flatNumber: 'C-202',
      commonArea: 'Wing C Corridor',
      residentName: 'Leela Roy',
      phone: '+91 98206 99001',
      photoUrl: '',
      duplicateOf: null,
      reportCount: 1,
      assignedTo: 'Society Electrician',
      needsManualTriage: false,
      aiOverridden: false,
      slaDueAt: daysAgo(18, -12),
      resolvedAt: daysAgo(18, -6),
      residentConfirmed: true,
      satisfactionRating: 5,
      isDemo: true,
      timeline: [
        { status: 'new', note: 'Breaker tripping reported', by: 'Leela Roy', at: daysAgo(18, 10) },
        { status: 'resolved', note: 'Faulty choke in tube fixture isolated and replaced', by: 'Electrician', at: daysAgo(18, 6) },
      ],
      internalNotes: [],
      createdAt: daysAgo(18, 10),
      updatedAt: daysAgo(18, 6),
    },

    // RESOLVED CLEANING ISSUE (2 days ago)
    {
      complaintId: 'SP-2026-0020',
      originalText: 'Wing A staircase landing dirty with construction dust from flat 303 renovation.',
      translatedText: 'Staircase dusty due to flat 303 ongoing renovation.',
      language: 'en',
      summary: 'Wing A staircase dusty from flat 303 renovation',
      category: 'cleaning',
      urgency: 'low',
      urgencyScore: 30,
      urgencyReason: 'Post-renovation dust cleaning',
      isSafetyRisk: false,
      status: 'resolved',
      wing: 'A',
      flatNumber: 'A-303',
      commonArea: 'Wing A Staircase',
      residentName: 'Pooja Bhatt',
      phone: '+91 98207 11223',
      photoUrl: '',
      duplicateOf: null,
      reportCount: 1,
      assignedTo: 'Housekeeping Supervisor',
      needsManualTriage: false,
      aiOverridden: false,
      slaDueAt: daysAgo(2, -24),
      resolvedAt: daysAgo(2, -4),
      residentConfirmed: true,
      satisfactionRating: 5,
      isDemo: true,
      timeline: [
        { status: 'new', note: 'Dust complaint logged', by: 'Pooja Bhatt', at: daysAgo(2, 8) },
        { status: 'resolved', note: 'Wet mopping completed by housekeeping staff', by: 'Supervisor', at: daysAgo(2, 4) },
      ],
      internalNotes: [],
      createdAt: daysAgo(2, 8),
      updatedAt: daysAgo(2, 4),
    },

    // RESOLVED PARKING ISSUE (10 days ago)
    {
      complaintId: 'SP-2026-0021',
      originalText: 'Wrong vehicle parked in slot B-09, blocking my motorcycle.',
      translatedText: 'Motorcycle blocked by wrongly parked car in slot B-09.',
      language: 'en',
      summary: 'Vehicle parked in wrong slot blocking two-wheeler',
      category: 'parking',
      urgency: 'medium',
      urgencyScore: 45,
      urgencyReason: 'Parking slot infringement',
      isSafetyRisk: false,
      status: 'resolved',
      wing: 'B',
      flatNumber: 'B-203',
      commonArea: 'Stilt Parking B-09',
      residentName: 'Anil Deshmukh',
      phone: '+91 98207 22334',
      photoUrl: '',
      duplicateOf: null,
      reportCount: 1,
      assignedTo: 'Security Guard',
      needsManualTriage: false,
      aiOverridden: false,
      slaDueAt: daysAgo(10, -12),
      resolvedAt: daysAgo(10, -2),
      residentConfirmed: true,
      satisfactionRating: 4,
      isDemo: true,
      timeline: [
        { status: 'new', note: 'Parking block reported', by: 'Anil Deshmukh', at: daysAgo(10, 4) },
        { status: 'resolved', note: 'Security called driver to relocate car to guest bay', by: 'Security', at: daysAgo(10, 2) },
      ],
      internalNotes: [],
      createdAt: daysAgo(10, 4),
      updatedAt: daysAgo(10, 2),
    },

    // RESOLVED SECURITY ISSUE (14 days ago)
    {
      complaintId: 'SP-2026-0022',
      originalText: 'CCTV camera #4 on 1st floor corridor blind spot angle knocked out of alignment.',
      translatedText: 'CCTV camera angle shifted in Wing C 1st floor.',
      language: 'en',
      summary: 'CCTV camera #4 misalignment in corridor',
      category: 'security',
      urgency: 'low',
      urgencyScore: 35,
      urgencyReason: 'Surveillance camera realignment',
      isSafetyRisk: false,
      status: 'resolved',
      wing: 'C',
      flatNumber: 'C-103',
      commonArea: 'Wing C 1st Floor Corridor',
      residentName: 'Girish Kulkarni',
      phone: '+91 98207 33445',
      photoUrl: '',
      duplicateOf: null,
      reportCount: 1,
      assignedTo: 'Security Supervisor',
      needsManualTriage: false,
      aiOverridden: false,
      slaDueAt: daysAgo(14, -24),
      resolvedAt: daysAgo(14, -8),
      residentConfirmed: true,
      satisfactionRating: 5,
      isDemo: true,
      timeline: [
        { status: 'new', note: 'Camera alignment issue', by: 'Girish Kulkarni', at: daysAgo(14, 12) },
        { status: 'resolved', note: 'Camera mount tightened and view re-checked on monitor', by: 'Security', at: daysAgo(14, 8) },
      ],
      internalNotes: [],
      createdAt: daysAgo(14, 12),
      updatedAt: daysAgo(14, 8),
    },

    // RESOLVED NOISE ISSUE (21 days ago)
    {
      complaintId: 'SP-2026-0023',
      originalText: 'Late night furniture dragging noise from flat A-501 after 11:30 PM.',
      translatedText: 'Late night furniture dragging noise disturbance.',
      language: 'en',
      summary: 'Late night furniture dragging noise in Flat A-501',
      category: 'noise',
      urgency: 'low',
      urgencyScore: 32,
      urgencyReason: 'Quiet hours courtesy reminder',
      isSafetyRisk: false,
      status: 'resolved',
      wing: 'A',
      flatNumber: 'A-501',
      commonArea: 'Wing A 5th Floor',
      residentName: 'Maya Sen',
      phone: '+91 98207 44556',
      photoUrl: '',
      duplicateOf: null,
      reportCount: 1,
      assignedTo: 'Vikram Malhotra',
      needsManualTriage: false,
      aiOverridden: false,
      slaDueAt: daysAgo(21, -24),
      resolvedAt: daysAgo(21, -12),
      residentConfirmed: true,
      satisfactionRating: 4,
      isDemo: true,
      timeline: [
        { status: 'new', note: 'Noise complaint logged', by: 'Maya Sen', at: daysAgo(21, 16) },
        { status: 'resolved', note: 'Spoke with flat owner; carpet pads installed under chairs', by: 'Vikram Malhotra', at: daysAgo(21, 12) },
      ],
      internalNotes: [],
      createdAt: daysAgo(21, 16),
      updatedAt: daysAgo(21, 12),
    },

    // RESOLVED WATER ISSUE (28 days ago)
    {
      complaintId: 'SP-2026-0024',
      originalText: 'Garden sprinkler pipe ruptured near clubhouse gate.',
      translatedText: 'Garden sprinkler pipe burst near clubhouse.',
      language: 'en',
      summary: 'Garden sprinkler pipe burst near clubhouse',
      category: 'water',
      urgency: 'medium',
      urgencyScore: 50,
      urgencyReason: 'Common area landscape water line rupture',
      isSafetyRisk: false,
      status: 'resolved',
      wing: 'A',
      flatNumber: 'Clubhouse',
      commonArea: 'Garden Lawn',
      residentName: 'Ashok Kumar',
      phone: '+91 98207 55667',
      photoUrl: '',
      duplicateOf: null,
      reportCount: 1,
      assignedTo: 'Plumbing Service Desk',
      needsManualTriage: false,
      aiOverridden: false,
      slaDueAt: daysAgo(28, -12),
      resolvedAt: daysAgo(28, -6),
      residentConfirmed: true,
      satisfactionRating: 5,
      isDemo: true,
      timeline: [
        { status: 'new', note: 'Sprinkler burst reported', by: 'Ashok Kumar', at: daysAgo(28, 10) },
        { status: 'resolved', note: 'PVC pipe section replaced and re-buried', by: 'Plumber', at: daysAgo(28, 6) },
      ],
      internalNotes: [],
      createdAt: daysAgo(28, 10),
      updatedAt: daysAgo(28, 6),
    },

    // ----------------- ADDITIONAL VARIED HISTORICAL COMPLAINTS (~6 MORE TO REACH ~30) -----------------
    {
      complaintId: 'SP-2026-0025',
      originalText: 'जिम का ट्रेडमिल 2 नंबर एरर कोड E-02 दिखा रहा है।',
      translatedText: 'Gym treadmill #2 showing error code E-02.',
      language: 'hi',
      summary: 'Gym treadmill #2 error code E-02',
      category: 'other',
      urgency: 'low',
      urgencyScore: 25,
      urgencyReason: 'Recreational gym equipment fault',
      isSafetyRisk: false,
      status: 'resolved',
      wing: 'C',
      flatNumber: 'Clubhouse',
      commonArea: 'Gymnasium',
      residentName: 'Vikas Dubey',
      phone: '+91 98207 66778',
      photoUrl: '',
      duplicateOf: null,
      reportCount: 1,
      assignedTo: 'Fitness Equipment Vendor',
      needsManualTriage: false,
      aiOverridden: false,
      slaDueAt: daysAgo(15, -48),
      resolvedAt: daysAgo(15, -24),
      residentConfirmed: true,
      satisfactionRating: 4,
      isDemo: true,
      timeline: [
        { status: 'new', note: 'Reported treadmill error in Hindi', by: 'Vikas Dubey', at: daysAgo(15, 30) },
        { status: 'resolved', note: 'Speed sensor replaced by vendor', by: 'Vendor', at: daysAgo(15, 24) },
      ],
      internalNotes: [],
      createdAt: daysAgo(15, 30),
      updatedAt: daysAgo(15, 24),
    },
    {
      complaintId: 'SP-2026-0026',
      originalText: 'Wing B terrace door lock jammed, unable to inspect solar panels.',
      translatedText: 'Wing B terrace door lock jammed.',
      language: 'en',
      summary: 'Wing B terrace door lock jammed',
      category: 'security',
      urgency: 'low',
      urgencyScore: 30,
      urgencyReason: 'Access door latch maintenance',
      isSafetyRisk: false,
      status: 'resolved',
      wing: 'B',
      flatNumber: 'B-Terrace',
      commonArea: 'Wing B Terrace',
      residentName: 'Prakash Rao',
      phone: '+91 98207 77889',
      photoUrl: '',
      duplicateOf: null,
      reportCount: 1,
      assignedTo: 'Society Carpenter',
      needsManualTriage: false,
      aiOverridden: false,
      slaDueAt: daysAgo(9, -24),
      resolvedAt: daysAgo(9, -8),
      residentConfirmed: true,
      satisfactionRating: 5,
      isDemo: true,
      timeline: [
        { status: 'new', note: 'Terrace lock issue', by: 'Prakash Rao', at: daysAgo(9, 12) },
        { status: 'resolved', note: 'Lock cylinder lubricated and latch aligned', by: 'Carpenter', at: daysAgo(9, 8) },
      ],
      internalNotes: [],
      createdAt: daysAgo(9, 12),
      updatedAt: daysAgo(9, 8),
    },
    {
      complaintId: 'SP-2026-0027',
      originalText: 'Street lamp pole #3 near B-wing ramp flickering constantly.',
      translatedText: 'Street lamp flickering on Wing B ramp.',
      language: 'en',
      summary: 'Flickering street lamp pole on Wing B ramp',
      category: 'electrical',
      urgency: 'low',
      urgencyScore: 28,
      urgencyReason: 'Outdoor perimeter lighting fixture flicker',
      isSafetyRisk: false,
      status: 'resolved',
      wing: 'B',
      flatNumber: 'Compound',
      commonArea: 'Driveway Ramp',
      residentName: 'Sunil Gavaskar',
      phone: '+91 98207 88990',
      photoUrl: '',
      duplicateOf: null,
      reportCount: 1,
      assignedTo: 'Society Electrician',
      needsManualTriage: false,
      aiOverridden: false,
      slaDueAt: daysAgo(11, -48),
      resolvedAt: daysAgo(11, -12),
      residentConfirmed: true,
      satisfactionRating: 4,
      isDemo: true,
      timeline: [
        { status: 'new', note: 'Flickering light reported', by: 'Sunil Gavaskar', at: daysAgo(11, 20) },
        { status: 'resolved', note: 'LED driver ballast replaced', by: 'Electrician', at: daysAgo(11, 12) },
      ],
      internalNotes: [],
      createdAt: daysAgo(11, 20),
      updatedAt: daysAgo(11, 12),
    },
    {
      complaintId: 'SP-2026-0028',
      originalText: 'Basement recycling bin overfilled with cardboard boxes from weekend deliveries.',
      translatedText: 'Basement recycling bin overfilled with packaging boxes.',
      language: 'en',
      summary: 'Overfilled cardboard recycling bin in basement',
      category: 'cleaning',
      urgency: 'low',
      urgencyScore: 22,
      urgencyReason: 'Routine dry waste clearance',
      isSafetyRisk: false,
      status: 'resolved',
      wing: 'C',
      flatNumber: 'Basement',
      commonArea: 'Waste Segregation Area',
      residentName: 'Geeta Merchant',
      phone: '+91 98207 99001',
      photoUrl: '',
      duplicateOf: null,
      reportCount: 1,
      assignedTo: 'Housekeeping Staff',
      needsManualTriage: false,
      aiOverridden: false,
      slaDueAt: daysAgo(6, -24),
      resolvedAt: daysAgo(6, -4),
      residentConfirmed: true,
      satisfactionRating: 5,
      isDemo: true,
      timeline: [
        { status: 'new', note: 'Recycling bin full', by: 'Geeta Merchant', at: daysAgo(6, 8) },
        { status: 'resolved', note: 'Cardboards tied and cleared for scrap vendor', by: 'Housekeeping', at: daysAgo(6, 4) },
      ],
      internalNotes: [],
      createdAt: daysAgo(6, 8),
      updatedAt: daysAgo(6, 4),
    },
    {
      complaintId: 'SP-2026-0029',
      originalText: 'Water tanker delivery driver parked across the main compound thoroughfare.',
      translatedText: 'Water tanker driver blocking society compound lane.',
      language: 'en',
      summary: 'Water tanker blocking main compound lane',
      category: 'parking',
      urgency: 'medium',
      urgencyScore: 48,
      urgencyReason: 'Thoroughfare vehicular blockage',
      isSafetyRisk: false,
      status: 'resolved',
      wing: 'A',
      flatNumber: 'Internal Road',
      commonArea: 'Main Compound',
      residentName: 'Sanjay Dutt',
      phone: '+91 98208 11223',
      photoUrl: '',
      duplicateOf: null,
      reportCount: 1,
      assignedTo: 'Security Head',
      needsManualTriage: false,
      aiOverridden: false,
      slaDueAt: daysAgo(8, -12),
      resolvedAt: daysAgo(8, -1),
      residentConfirmed: true,
      satisfactionRating: 4,
      isDemo: true,
      timeline: [
        { status: 'new', note: 'Tanker block reported', by: 'Sanjay Dutt', at: daysAgo(8, 3) },
        { status: 'resolved', note: 'Tanker directed to designated pump discharge bay', by: 'Security Head', at: daysAgo(8, 1) },
      ],
      internalNotes: [],
      createdAt: daysAgo(8, 3),
      updatedAt: daysAgo(8, 1),
    },
    {
      complaintId: 'SP-2026-0030',
      originalText: 'Visitor badge printer at security gate has paper jam.',
      translatedText: 'Visitor pass printer has paper jam at gate.',
      language: 'en',
      summary: 'Visitor badge printer paper jam at Gate 1',
      category: 'security',
      urgency: 'low',
      urgencyScore: 20,
      urgencyReason: 'Gate desk peripheral maintenance',
      isSafetyRisk: false,
      status: 'resolved',
      wing: 'A',
      flatNumber: 'Gate 1',
      commonArea: 'Security Gate Cabin',
      residentName: 'Security Desk',
      phone: '+91 98208 22334',
      photoUrl: '',
      duplicateOf: null,
      reportCount: 1,
      assignedTo: 'IT Maintenance',
      needsManualTriage: false,
      aiOverridden: false,
      slaDueAt: daysAgo(17, -48),
      resolvedAt: daysAgo(17, -5),
      residentConfirmed: true,
      satisfactionRating: 5,
      isDemo: true,
      timeline: [
        { status: 'new', note: 'Printer jam reported', by: 'Security Guard', at: daysAgo(17, 8) },
        { status: 'resolved', note: 'Roller roller cleaned and paper reload completed', by: 'Admin Assistant', at: daysAgo(17, 5) },
      ],
      internalNotes: [],
      createdAt: daysAgo(17, 8),
      updatedAt: daysAgo(17, 5),
    },
  ];

  // Database Execution
  await UserModel.deleteMany({});
  await UserModel.create(users);
  console.log(`✅ Seeded ${users.length} authorized committee users (admin@society.org, secretary@society.org, treasurer@society.org).`);

  await SettingsModel.deleteMany({});
  await SettingsModel.create(sampleSettings);
  console.log('✅ Seeded society configuration & SLA policies with configurable helplines.');

  await ComplaintModel.deleteMany({});
  await ComplaintModel.create(complaints);
  console.log(`✅ Seeded ${complaints.length} complaints with isDemo: true, recurring Lift B breakdowns (4x), and multi-lingual reports.`);

  // Generate Today's Autonomous Digest Record
  const todayStr = new Date().toISOString().split('T')[0];
  await DigestModel.deleteMany({ date: todayStr });

  const openList = complaints.filter((c) => c.status !== 'resolved' && c.status !== 'rejected');
  const criticalList = openList.filter((c) => c.urgency === 'critical');
  const highList = openList.filter((c) => c.urgency === 'high');
  const medList = openList.filter((c) => c.urgency === 'medium');
  const lowList = openList.filter((c) => c.urgency === 'low');

  const digestDoc = {
    date: todayStr,
    stats: {
      urgentCount: criticalList.length + highList.length,
      newCount: openList.filter((c) => c.status === 'new').length,
      overdueCount: 0,
      mergedDuplicatesCount: 4,
      totalOpenCount: openList.length,
    },
    summaryHeadline:
      'CRITICAL: Wing B electrical sparks in meter room & recurring Lift B motor outage. Domestic water supply in Wing A currently under repair.',
    rows: openList.slice(0, 10).map((c) => ({
      complaintId: c.complaintId,
      summary: c.summary,
      urgency: c.urgency,
      category: c.category,
      flatNumber: c.flatNumber,
      wing: c.wing,
      status: c.status,
      isSafetyRisk: c.isSafetyRisk,
      suggestedAction:
        c.category === 'electrical'
          ? 'Isolate main breaker and dispatch licensed electrician'
          : c.category === 'lift'
          ? 'Call Otis AMC breakdown dispatch immediately'
          : c.category === 'water'
          ? 'Inspect riser pump and order tanker'
          : 'Security team to inspect location',
    })),
  };

  await DigestModel.create(digestDoc);
  console.log("✅ Seeded Today's Autonomous 5-Minute Committee Digest.");

  return {
    success: true,
    userCount: users.length,
    complaintCount: complaints.length,
  };
}
