import bcrypt from 'bcryptjs';
import { connectDB } from '../lib/db';
import ComplaintModel from '../models/Complaint';
import UserModel from '../models/User';
import DigestModel from '../models/Digest';
import SettingsModel from '../models/Settings';
import fs from 'fs';
import path from 'path';
import { IComplaint, IUser, IDigest } from '../types';

async function seed() {
  console.log('🌱 Starting SocietyPulse Database Seed...');

  const passwordHashAdmin = await bcrypt.hash('admin123', 10);
  const passwordHashMember = await bcrypt.hash('member123', 10);

  const users: IUser[] = [
    {
      name: 'Vikram Malhotra',
      email: 'admin@society.org',
      passwordHash: passwordHashAdmin,
      role: 'admin',
      phone: '+91 98201 23456',
      createdAt: new Date().toISOString(),
    },
    {
      name: 'Ananya Deshmukh',
      email: 'secretary@society.org',
      passwordHash: passwordHashMember,
      role: 'member',
      phone: '+91 98202 34567',
      createdAt: new Date().toISOString(),
    },
    {
      name: 'Rajesh Nair',
      email: 'treasurer@society.org',
      passwordHash: passwordHashMember,
      role: 'member',
      phone: '+91 98203 45678',
      createdAt: new Date().toISOString(),
    },
  ];

  const now = new Date();
  const hoursAgo = (h: number) => new Date(now.getTime() - h * 60 * 60 * 1000);
  const hoursAhead = (h: number) => new Date(now.getTime() + h * 60 * 60 * 1000);

  const sampleComplaints: IComplaint[] = [
    {
      complaintId: 'SP-2026-0001',
      originalText: 'Wing B meter box se continuous sparks nikal rahe hain aur plastic jalne ki smell aa rahi hai!',
      translatedText: 'Continuous sparks are coming from Wing B meter box and there is a burning plastic smell!',
      language: 'hinglish',
      summary: 'Meter box sparking with burning smell',
      category: 'electrical',
      urgency: 'critical',
      urgencyScore: 98,
      urgencyReason: 'Active electrical sparking poses immediate fire hazard to building',
      isSafetyRisk: true,
      status: 'in_progress',
      wing: 'B',
      flatNumber: 'B-101',
      commonArea: 'Ground Floor Meter Room',
      residentName: 'Arun Verma',
      phone: '+91 98210 11111',
      assignedTo: 'Vikram Malhotra (Admin)',
      reportCount: 1,
      duplicateOf: null,
      needsManualTriage: false,
      aiOverridden: false,
      slaDueAt: hoursAhead(1),
      timeline: [
        { status: 'new', note: 'Complaint received via voice recording in Hinglish', by: 'System', at: hoursAgo(1.5) },
        { status: 'triaged', note: 'AI flagged Critical Fire & Safety Hazard. Urgency score 98.', by: 'AI Triage', at: hoursAgo(1.4) },
        { status: 'assigned', note: 'Assigned to Electrician Mr. Santosh & Vikram Malhotra', by: 'Secretary', at: hoursAgo(1) },
        { status: 'in_progress', note: 'Main breaker isolated. Replacement fuses being installed.', by: 'Vikram Malhotra', at: hoursAgo(0.5) },
      ],
      internalNotes: [
        { note: 'Adani Electricity emergency helpline was called as backup.', author: 'Vikram Malhotra', createdAt: hoursAgo(0.8) },
      ],
      createdAt: hoursAgo(1.5).toISOString(),
      updatedAt: hoursAgo(0.5).toISOString(),
    },
    {
      complaintId: 'SP-2026-0002',
      originalText: 'Lift B band hai subah se, elderly people cannot take stairs to 7th and 8th floor.',
      translatedText: 'Lift B has been broken since morning, senior citizens cannot take stairs.',
      language: 'hinglish',
      summary: 'Wing B passenger elevator out of service',
      category: 'lift',
      urgency: 'high',
      urgencyScore: 84,
      urgencyReason: 'High floor residents and elderly stranded without vertical mobility',
      isSafetyRisk: false,
      status: 'assigned',
      wing: 'B',
      flatNumber: 'B-702',
      commonArea: 'Wing B Elevator Shaft',
      residentName: 'Kavita Joshi',
      phone: '+91 98210 22222',
      assignedTo: 'Otis AMC Technician',
      reportCount: 3,
      duplicateOf: null,
      needsManualTriage: false,
      aiOverridden: false,
      slaDueAt: hoursAhead(4),
      timeline: [
        { status: 'new', note: 'Complaint reported by Flat B-702', by: 'System', at: hoursAgo(4) },
        { status: 'triaged', note: 'AI detected High priority elevator outage', by: 'AI Triage', at: hoursAgo(3.9) },
        { status: 'assigned', note: 'Ticket #OTIS-4491 logged with Otis service engineer', by: 'Ananya Deshmukh', at: hoursAgo(2) },
      ],
      internalNotes: [],
      createdAt: hoursAgo(4).toISOString(),
      updatedAt: hoursAgo(2).toISOString(),
    },
    {
      complaintId: 'SP-2026-0003',
      originalText: 'Lift B nahi chal rahi hai, ground floor par atki hai.',
      translatedText: 'Lift B is not working, stuck on ground floor.',
      language: 'hinglish',
      summary: 'Lift B stuck on ground floor',
      category: 'lift',
      urgency: 'high',
      urgencyScore: 82,
      urgencyReason: 'Duplicate of SP-2026-0002',
      isSafetyRisk: false,
      status: 'assigned',
      wing: 'B',
      flatNumber: 'B-404',
      commonArea: 'Wing B Elevator',
      residentName: 'Sunil Rao',
      phone: '+91 98210 33333',
      duplicateOf: 'SP-2026-0002',
      reportCount: 1,
      assignedTo: 'Otis AMC Technician',
      needsManualTriage: false,
      aiOverridden: false,
      slaDueAt: hoursAhead(4),
      timeline: [
        { status: 'new', note: 'Submitted via Web', by: 'System', at: hoursAgo(3) },
        { status: 'triaged', note: 'AI matched semantic duplicate with parent SP-2026-0002', by: 'AI Triage', at: hoursAgo(2.9) },
      ],
      internalNotes: [],
      createdAt: hoursAgo(3).toISOString(),
      updatedAt: hoursAgo(2.9).toISOString(),
    },
    {
      complaintId: 'SP-2026-0004',
      originalText: 'No water supply in entire Wing A since 6 AM! Tanker required urgently.',
      translatedText: 'No water supply in entire Wing A since 6 AM! Tanker required urgently.',
      language: 'en',
      summary: 'Complete water outage in Wing A',
      category: 'water',
      urgency: 'critical',
      urgencyScore: 94,
      urgencyReason: 'Total loss of domestic water affecting 30+ families for several hours',
      isSafetyRisk: true,
      status: 'in_progress',
      wing: 'A',
      flatNumber: 'A-201',
      commonArea: 'Wing A Main Header Line',
      residentName: 'Meera Iyer',
      phone: '+91 98210 44444',
      assignedTo: 'Rajesh Nair (Treasurer)',
      reportCount: 4,
      duplicateOf: null,
      needsManualTriage: false,
      aiOverridden: false,
      slaDueAt: hoursAhead(1),
      timeline: [
        { status: 'new', note: 'Reported by Flat A-201', by: 'System', at: hoursAgo(5) },
        { status: 'triaged', note: 'AI flagged Critical Domestic Water outage', by: 'AI Triage', at: hoursAgo(4.8) },
        { status: 'assigned', note: 'Assigned to Plumber & Water Committee', by: 'Rajesh Nair', at: hoursAgo(4) },
        { status: 'in_progress', note: 'Submersible pump motor tripping issue identified. 2 water tankers ordered.', by: 'Rajesh Nair', at: hoursAgo(2) },
      ],
      internalNotes: [
        { note: 'Paid advance of Rs 2400 for emergency tanker delivery.', author: 'Rajesh Nair', createdAt: hoursAgo(2) },
      ],
      createdAt: hoursAgo(5).toISOString(),
      updatedAt: hoursAgo(2).toISOString(),
    },
    {
      complaintId: 'SP-2026-0005',
      originalText: 'Wing A me subah se nalke sukhe hain, pani kab aayega?',
      translatedText: 'Taps are dry in Wing A since morning, when will water come?',
      language: 'hinglish',
      summary: 'Wing A taps dry duplicate report',
      category: 'water',
      urgency: 'critical',
      urgencyScore: 92,
      urgencyReason: 'Duplicate of SP-2026-0004',
      isSafetyRisk: true,
      status: 'in_progress',
      wing: 'A',
      flatNumber: 'A-503',
      commonArea: 'Wing A Overhead Tank',
      residentName: 'Deepak Shah',
      phone: '+91 98210 55555',
      duplicateOf: 'SP-2026-0004',
      reportCount: 1,
      assignedTo: 'Rajesh Nair (Treasurer)',
      needsManualTriage: false,
      aiOverridden: false,
      slaDueAt: hoursAhead(1),
      timeline: [
        { status: 'new', note: 'Submitted via Hindi voice input', by: 'System', at: hoursAgo(4.5) },
        { status: 'triaged', note: 'AI merged into existing incident SP-2026-0004', by: 'AI Triage', at: hoursAgo(4.4) },
      ],
      internalNotes: [],
      createdAt: hoursAgo(4.5).toISOString(),
      updatedAt: hoursAgo(4.4).toISOString(),
    },
    {
      complaintId: 'SP-2026-0006',
      originalText: 'Basement 2 slot P-44 me ek unknown white Swift car park hai, mera reserved slot block hai.',
      translatedText: 'An unknown white Swift is parked in Basement 2 slot P-44, blocking my reserved slot.',
      language: 'hinglish',
      summary: 'Unauthorized vehicle blocking reserved parking slot P-44',
      category: 'parking',
      urgency: 'medium',
      urgencyScore: 58,
      urgencyReason: 'Resident unable to park personal vehicle in allocated bay',
      isSafetyRisk: false,
      status: 'new',
      wing: 'C',
      flatNumber: 'C-302',
      commonArea: 'Basement 2, Slot P-44',
      residentName: 'Prateek Singhania',
      phone: '+91 98210 66666',
      duplicateOf: null,
      reportCount: 1,
      needsManualTriage: false,
      aiOverridden: false,
      slaDueAt: hoursAhead(20),
      timeline: [
        { status: 'new', note: 'Complaint logged with photo of vehicle license plate', by: 'System', at: hoursAgo(3) },
        { status: 'triaged', note: 'AI classified under Parking violations', by: 'AI Triage', at: hoursAgo(2.9) },
      ],
      internalNotes: [],
      createdAt: hoursAgo(3).toISOString(),
      updatedAt: hoursAgo(2.9).toISOString(),
    },
    {
      complaintId: 'SP-2026-0007',
      originalText: 'C Wing staircase aur 4th floor corridor me kachra pada hai 2 din se, badbu aa rahi hai.',
      translatedText: 'Garbage lying on C Wing staircase and 4th floor corridor for 2 days, foul smell.',
      language: 'hinglish',
      summary: 'Uncollected garbage in Wing C corridor and staircase',
      category: 'cleaning',
      urgency: 'medium',
      urgencyScore: 62,
      urgencyReason: 'Hygiene issue causing foul smell in residential common passage',
      isSafetyRisk: false,
      status: 'assigned',
      wing: 'C',
      flatNumber: 'C-401',
      commonArea: '4th Floor Staircase',
      residentName: 'Swati Sen',
      phone: '+91 98210 77777',
      assignedTo: 'Mahesh (Housekeeping Supervisor)',
      duplicateOf: null,
      reportCount: 1,
      needsManualTriage: false,
      aiOverridden: false,
      slaDueAt: hoursAhead(18),
      timeline: [
        { status: 'new', note: 'Resident reported via mobile wizard', by: 'System', at: hoursAgo(6) },
        { status: 'triaged', note: 'AI classified under Cleaning & Hygiene', by: 'AI Triage', at: hoursAgo(5.8) },
        { status: 'assigned', note: 'Assigned to Housekeeping staff for midday sweep', by: 'Ananya Deshmukh', at: hoursAgo(3) },
      ],
      internalNotes: [],
      createdAt: hoursAgo(6).toISOString(),
      updatedAt: hoursAgo(3).toISOString(),
    },
    {
      complaintId: 'SP-2026-0008',
      originalText: 'Main security gate 1 barrier sensor is broken and arm is tied with rope.',
      translatedText: 'Main security gate 1 barrier sensor is broken and arm is tied with rope.',
      language: 'en',
      summary: 'Main gate boom barrier sensor broken',
      category: 'security',
      urgency: 'high',
      urgencyScore: 76,
      urgencyReason: 'Compromised vehicle access control at society entrance',
      isSafetyRisk: false,
      status: 'assigned',
      wing: 'D',
      flatNumber: 'D-102',
      commonArea: 'Main Entrance Gate 1',
      residentName: 'Captain Ramesh Bhatia',
      phone: '+91 98210 88888',
      assignedTo: 'SecurePlus Automation Agency',
      duplicateOf: null,
      reportCount: 1,
      needsManualTriage: false,
      aiOverridden: false,
      slaDueAt: hoursAhead(5),
      timeline: [
        { status: 'new', note: 'Reported by Capt. Bhatia', by: 'System', at: hoursAgo(8) },
        { status: 'triaged', note: 'AI classified as High security priority', by: 'AI Triage', at: hoursAgo(7.9) },
        { status: 'assigned', note: 'Boom barrier vendor contacted for sensor replacement', by: 'Vikram Malhotra', at: hoursAgo(4) },
      ],
      internalNotes: [],
      createdAt: hoursAgo(8).toISOString(),
      updatedAt: hoursAgo(4).toISOString(),
    },
    {
      complaintId: 'SP-2026-0009',
      originalText: 'Flat D-604 is playing loud bass music past midnight every Saturday.',
      translatedText: 'Flat D-604 is playing loud bass music past midnight every Saturday.',
      language: 'en',
      summary: 'Late night loud music disturbance from D-604',
      category: 'noise',
      urgency: 'medium',
      urgencyScore: 48,
      urgencyReason: 'Noise violation during society quiet hours (after 11 PM)',
      isSafetyRisk: false,
      status: 'new',
      wing: 'D',
      flatNumber: 'D-603',
      commonArea: '6th Floor Corridor',
      residentName: 'Tanvi Agarwal',
      phone: '+91 98210 99999',
      duplicateOf: null,
      reportCount: 1,
      needsManualTriage: false,
      aiOverridden: false,
      slaDueAt: hoursAhead(22),
      timeline: [
        { status: 'new', note: 'Submitted via web portal', by: 'System', at: hoursAgo(2) },
        { status: 'triaged', note: 'AI categorised under Noise & Nuisance', by: 'AI Triage', at: hoursAgo(1.9) },
      ],
      internalNotes: [],
      createdAt: hoursAgo(2).toISOString(),
      updatedAt: hoursAgo(1.9).toISOString(),
    },
    {
      complaintId: 'SP-2026-0010',
      originalText: 'Gym treadmill belt is slipping and making loud squeaking sound.',
      translatedText: 'Gym treadmill belt is slipping and making loud squeaking sound.',
      language: 'en',
      summary: 'Clubhouse gym treadmill belt slipping',
      category: 'other',
      urgency: 'low',
      urgencyScore: 30,
      urgencyReason: 'Routine equipment wear and tear, no safety hazard',
      isSafetyRisk: false,
      status: 'resolved',
      wing: 'A',
      flatNumber: 'A-304',
      commonArea: 'Clubhouse Gym',
      residentName: 'Kunal Kapoor',
      phone: '+91 98211 00000',
      assignedTo: 'FitTech Equipment Care',
      duplicateOf: null,
      reportCount: 1,
      needsManualTriage: false,
      aiOverridden: false,
      slaDueAt: hoursAgo(10),
      resolvedAt: hoursAgo(4),
      residentConfirmed: true,
      timeline: [
        { status: 'new', note: 'Logged by resident', by: 'System', at: hoursAgo(30) },
        { status: 'assigned', note: 'Gym technician assigned', by: 'Secretary', at: hoursAgo(24) },
        { status: 'in_progress', note: 'Belt lubricant applied & tension recalibrated', by: 'FitTech', at: hoursAgo(6) },
        { status: 'resolved', note: 'Resident tested and confirmed working smoothly', by: 'Kunal Kapoor', at: hoursAgo(4) },
      ],
      internalNotes: [],
      createdAt: hoursAgo(30).toISOString(),
      updatedAt: hoursAgo(4).toISOString(),
    },
    {
      complaintId: 'SP-2026-0011',
      originalText: 'Terrace garden tap is leaking continuously, water dripping into B-801 ceiling.',
      translatedText: 'Terrace garden tap leaking continuously, water dripping into B-801 ceiling.',
      language: 'hinglish',
      summary: 'Terrace tap leakage causing seepage in B-801',
      category: 'water',
      urgency: 'high',
      urgencyScore: 78,
      urgencyReason: 'Ongoing water seepage causing structural damage to top floor flat ceiling',
      isSafetyRisk: false,
      status: 'in_progress',
      wing: 'B',
      flatNumber: 'B-801',
      commonArea: 'Wing B Terrace Garden',
      residentName: 'Harish Mehta',
      phone: '+91 98211 11111',
      assignedTo: 'Plumbing Team',
      duplicateOf: null,
      reportCount: 1,
      needsManualTriage: false,
      aiOverridden: false,
      slaDueAt: hoursAhead(2),
      timeline: [
        { status: 'new', note: 'Reported with photos of wet ceiling', by: 'System', at: hoursAgo(12) },
        { status: 'assigned', note: 'Plumber inspected terrace supply line', by: 'Rajesh Nair', at: hoursAgo(6) },
        { status: 'in_progress', note: 'Terrace valve replaced, waterproofing primer applied', by: 'Plumber', at: hoursAgo(1) },
      ],
      internalNotes: [],
      createdAt: hoursAgo(12).toISOString(),
      updatedAt: hoursAgo(1).toISOString(),
    },
    {
      complaintId: 'SP-2026-0012',
      originalText: 'Wing C lift door closes too fast and hit a child today afternoon.',
      translatedText: 'Wing C elevator door closes too fast and bumped a child today afternoon.',
      language: 'en',
      summary: 'Wing C elevator door sensor closing aggressively',
      category: 'lift',
      urgency: 'critical',
      urgencyScore: 91,
      urgencyReason: 'Safety hazard: sensor failure causing physical impact on passengers',
      isSafetyRisk: true,
      status: 'in_progress',
      wing: 'C',
      flatNumber: 'C-204',
      commonArea: 'Wing C Lift',
      residentName: 'Neha Bansal',
      phone: '+91 98211 22222',
      assignedTo: 'Otis AMC Engineer',
      duplicateOf: null,
      reportCount: 1,
      needsManualTriage: false,
      aiOverridden: false,
      slaDueAt: hoursAhead(1),
      timeline: [
        { status: 'new', note: 'Logged by resident', by: 'System', at: hoursAgo(3) },
        { status: 'triaged', note: 'AI marked Critical Safety Risk (Elevator Door Sensor)', by: 'AI Triage', at: hoursAgo(2.9) },
        { status: 'assigned', note: 'Emergency call to Otis Lift AMC', by: 'Ananya Deshmukh', at: hoursAgo(2.5) },
        { status: 'in_progress', note: 'Curtain sensor re-alignment in progress', by: 'Otis Tech', at: hoursAgo(0.5) },
      ],
      internalNotes: [],
      createdAt: hoursAgo(3).toISOString(),
      updatedAt: hoursAgo(0.5).toISOString(),
    },
    {
      complaintId: 'SP-2026-0013',
      originalText: 'Society garden me street lights sham ko on nahi ho rahi hain, andhera rehta hai.',
      translatedText: 'Garden street lights are not turning on in the evening, pitch dark.',
      language: 'hinglish',
      summary: 'Garden pathway lights timer faulty',
      category: 'electrical',
      urgency: 'medium',
      urgencyScore: 52,
      urgencyReason: 'Dim pathways increase trip hazards for evening walking seniors',
      isSafetyRisk: false,
      status: 'assigned',
      wing: 'D',
      flatNumber: 'D-301',
      commonArea: 'Central Garden Path',
      residentName: 'Govind Kulkarni',
      phone: '+91 98211 33333',
      assignedTo: 'Santosh (Society Electrician)',
      duplicateOf: null,
      reportCount: 1,
      needsManualTriage: false,
      aiOverridden: false,
      slaDueAt: hoursAhead(16),
      timeline: [
        { status: 'new', note: 'Logged by resident', by: 'System', at: hoursAgo(10) },
        { status: 'assigned', note: 'Electrician requested to replace dusk-to-dawn sensor timer', by: 'Secretary', at: hoursAgo(4) },
      ],
      internalNotes: [],
      createdAt: hoursAgo(10).toISOString(),
      updatedAt: hoursAgo(4).toISOString(),
    },
    {
      complaintId: 'SP-2026-0014',
      originalText: 'Pani me halka mitti jaisa colour aa raha hai Wing D line me.',
      translatedText: 'Muddy brownish water coming from taps in Wing D.',
      language: 'hinglish',
      summary: 'Turbid muddy water in Wing D taps',
      category: 'water',
      urgency: 'high',
      urgencyScore: 74,
      urgencyReason: 'Contaminated tap water risks drinking safety of residents',
      isSafetyRisk: true,
      status: 'new',
      wing: 'D',
      flatNumber: 'D-502',
      commonArea: 'Wing D Overhead Storage Tank',
      residentName: 'Anita Roy',
      phone: '+91 98211 44444',
      duplicateOf: null,
      reportCount: 2,
      needsManualTriage: false,
      aiOverridden: false,
      slaDueAt: hoursAhead(3),
      timeline: [
        { status: 'new', note: 'Reported with photo of brownish water in glass', by: 'System', at: hoursAgo(2) },
        { status: 'triaged', note: 'AI flagged Drinking Water Safety concern', by: 'AI Triage', at: hoursAgo(1.9) },
      ],
      internalNotes: [],
      createdAt: hoursAgo(2).toISOString(),
      updatedAt: hoursAgo(1.9).toISOString(),
    },
    {
      complaintId: 'SP-2026-0015',
      originalText: 'Wing D nalke me ganda pani aa raha hai.',
      translatedText: 'Dirty water coming in Wing D tap.',
      language: 'hinglish',
      summary: 'Wing D dirty tap water duplicate',
      category: 'water',
      urgency: 'high',
      urgencyScore: 72,
      urgencyReason: 'Duplicate of SP-2026-0014',
      isSafetyRisk: true,
      status: 'new',
      wing: 'D',
      flatNumber: 'D-401',
      commonArea: 'Wing D Line',
      residentName: 'Sanjay Gupta',
      phone: '+91 98211 55555',
      duplicateOf: 'SP-2026-0014',
      reportCount: 1,
      needsManualTriage: false,
      aiOverridden: false,
      slaDueAt: hoursAhead(3),
      timeline: [
        { status: 'new', note: 'Submitted via mobile', by: 'System', at: hoursAgo(1) },
        { status: 'triaged', note: 'AI linked duplicate to SP-2026-0014', by: 'AI Triage', at: hoursAgo(0.9) },
      ],
      internalNotes: [],
      createdAt: hoursAgo(1).toISOString(),
      updatedAt: hoursAgo(0.9).toISOString(),
    },
    {
      complaintId: 'SP-2026-0016',
      originalText: 'Basement entry ramp has oil spill from a leaking tempo, two 2-wheelers skidded today!',
      translatedText: 'Basement entry ramp has oil spill, two 2-wheelers skidded!',
      language: 'en',
      summary: 'Slippery oil spill on basement vehicle ramp',
      category: 'cleaning',
      urgency: 'critical',
      urgencyScore: 95,
      urgencyReason: 'Severe skid hazard causing direct vehicle accidents on slope',
      isSafetyRisk: true,
      status: 'resolved',
      wing: 'A',
      flatNumber: 'A-102',
      commonArea: 'Basement 1 Entrance Ramp',
      residentName: 'Rohit Shenoy',
      phone: '+91 98211 66666',
      assignedTo: 'Ramesh (Housekeeping)',
      duplicateOf: null,
      reportCount: 1,
      needsManualTriage: false,
      aiOverridden: false,
      slaDueAt: hoursAgo(12),
      resolvedAt: hoursAgo(10),
      residentConfirmed: true,
      timeline: [
        { status: 'new', note: 'Urgent skid alert logged', by: 'System', at: hoursAgo(14) },
        { status: 'in_progress', note: 'Sand and chemical degreaser spread on ramp', by: 'Housekeeping', at: hoursAgo(12) },
        { status: 'resolved', note: 'Ramp thoroughly power-washed and dried with caution cones placed', by: 'Vikram Malhotra', at: hoursAgo(10) },
      ],
      internalNotes: [],
      createdAt: hoursAgo(14).toISOString(),
      updatedAt: hoursAgo(10).toISOString(),
    },
    {
      complaintId: 'SP-2026-0017',
      originalText: 'Fire hose reel box glass broken on 5th floor Wing A and nozzle missing.',
      translatedText: 'Fire hose reel box glass broken on 5th floor Wing A and nozzle missing.',
      language: 'en',
      summary: 'Fire fighting equipment damaged on 5th floor',
      category: 'security',
      urgency: 'high',
      urgencyScore: 86,
      urgencyReason: 'Compromised building fire fighting readiness',
      isSafetyRisk: true,
      status: 'assigned',
      wing: 'A',
      flatNumber: 'A-501',
      commonArea: '5th Floor Fire Hydrant Box',
      residentName: 'Priya Nambiar',
      phone: '+91 98211 77777',
      assignedTo: 'Fire Safety Equipment Vendor',
      duplicateOf: null,
      reportCount: 1,
      needsManualTriage: false,
      aiOverridden: false,
      slaDueAt: hoursAhead(4),
      timeline: [
        { status: 'new', note: 'Logged with photo of open fire box', by: 'System', at: hoursAgo(7) },
        { status: 'assigned', note: 'Security agency asked to review CCTV footage and replace nozzle', by: 'Secretary', at: hoursAgo(3) },
      ],
      internalNotes: [],
      createdAt: hoursAgo(7).toISOString(),
      updatedAt: hoursAgo(3).toISOString(),
    },
    {
      complaintId: 'SP-2026-0018',
      originalText: 'CCTV camera near lift lobby wing B is showing black screen.',
      translatedText: 'CCTV camera near lift lobby wing B is showing black screen.',
      language: 'en',
      summary: 'Wing B lobby CCTV camera offline',
      category: 'security',
      urgency: 'medium',
      urgencyScore: 56,
      urgencyReason: 'Surveillance blindspot in ground floor elevator lobby',
      isSafetyRisk: false,
      status: 'new',
      wing: 'B',
      flatNumber: 'B-103',
      commonArea: 'Wing B Ground Lobby',
      residentName: 'Tarun Khosla',
      phone: '+91 98211 88888',
      duplicateOf: null,
      reportCount: 1,
      needsManualTriage: false,
      aiOverridden: false,
      slaDueAt: hoursAhead(20),
      timeline: [
        { status: 'new', note: 'Reported by resident', by: 'System', at: hoursAgo(4) },
      ],
      internalNotes: [],
      createdAt: hoursAgo(4).toISOString(),
      updatedAt: hoursAgo(4).toISOString(),
    },
    {
      complaintId: 'SP-2026-0019',
      originalText: 'Children park swing chain rusted and broken, one swing missing.',
      translatedText: 'Children park swing chain rusted and broken, one swing missing.',
      language: 'en',
      summary: 'Kids play area swing chain broken',
      category: 'other',
      urgency: 'medium',
      urgencyScore: 50,
      urgencyReason: 'Physical injury risk for playing toddlers',
      isSafetyRisk: true,
      status: 'assigned',
      wing: 'C',
      flatNumber: 'C-102',
      commonArea: 'Children Play Area',
      residentName: 'Simran Jolly',
      phone: '+91 98211 99999',
      assignedTo: 'Garden Maintenance Agency',
      duplicateOf: null,
      reportCount: 1,
      needsManualTriage: false,
      aiOverridden: false,
      slaDueAt: hoursAhead(15),
      timeline: [
        { status: 'new', note: 'Reported via web form', by: 'System', at: hoursAgo(9) },
        { status: 'assigned', note: 'Work order given for stainless steel chain replacement', by: 'Secretary', at: hoursAgo(5) },
      ],
      internalNotes: [],
      createdAt: hoursAgo(9).toISOString(),
      updatedAt: hoursAgo(5).toISOString(),
    },
    {
      complaintId: 'SP-2026-0020',
      originalText: 'Intercom connection dead for past 4 days, cannot buzz delivery persons.',
      translatedText: 'Intercom connection dead for past 4 days, cannot buzz delivery persons.',
      language: 'en',
      summary: 'Flat D-202 intercom line dead',
      category: 'electrical',
      urgency: 'low',
      urgencyScore: 32,
      urgencyReason: 'Communication inconvenience for visitor authorization',
      isSafetyRisk: false,
      status: 'resolved',
      wing: 'D',
      flatNumber: 'D-202',
      commonArea: '',
      residentName: 'Vikas Saxena',
      phone: '+91 98212 00000',
      assignedTo: 'EPABX Technician',
      duplicateOf: null,
      reportCount: 1,
      needsManualTriage: false,
      aiOverridden: false,
      slaDueAt: hoursAgo(20),
      resolvedAt: hoursAgo(8),
      residentConfirmed: true,
      timeline: [
        { status: 'new', note: 'Reported by resident', by: 'System', at: hoursAgo(40) },
        { status: 'resolved', note: 'Junction box wire re-crimped. Intercom dialed gate successfully.', by: 'EPABX Technician', at: hoursAgo(8) },
      ],
      internalNotes: [],
      createdAt: hoursAgo(40).toISOString(),
      updatedAt: hoursAgo(8).toISOString(),
    },
    {
      complaintId: 'SP-2026-0021',
      originalText: 'Pigeon net torn on society duct behind kitchen, birds entering shaft.',
      translatedText: 'Pigeon net torn on society duct behind kitchen, birds entering shaft.',
      language: 'en',
      summary: 'Duct safety pigeon netting torn in Wing B',
      category: 'cleaning',
      urgency: 'low',
      urgencyScore: 28,
      urgencyReason: 'Bird nuisance and droppings accumulation in internal pipe shaft',
      isSafetyRisk: false,
      status: 'new',
      wing: 'B',
      flatNumber: 'B-303',
      commonArea: 'Wing B Rear Duct',
      residentName: 'Alok Pandey',
      phone: '+91 98212 11111',
      duplicateOf: null,
      reportCount: 1,
      needsManualTriage: false,
      aiOverridden: false,
      slaDueAt: hoursAhead(48),
      timeline: [
        { status: 'new', note: 'Logged by resident', by: 'System', at: hoursAgo(15) },
      ],
      internalNotes: [],
      createdAt: hoursAgo(15).toISOString(),
      updatedAt: hoursAgo(15).toISOString(),
    },
    {
      complaintId: 'SP-2026-0022',
      originalText: 'Swimming pool chlorine smell is extremely overpowering and burning eyes.',
      translatedText: 'Swimming pool chlorine smell is extremely overpowering and burning eyes.',
      language: 'en',
      summary: 'Excessive chemical chlorine dosage in swimming pool',
      category: 'other',
      urgency: 'medium',
      urgencyScore: 60,
      urgencyReason: 'Chemical dosing imbalance can cause skin and ocular irritation',
      isSafetyRisk: true,
      status: 'reopened',
      wing: 'A',
      flatNumber: 'A-402',
      commonArea: 'Clubhouse Swimming Pool',
      residentName: 'Divya Nair',
      phone: '+91 98212 22222',
      assignedTo: 'Pool Filtration Vendor',
      duplicateOf: null,
      reportCount: 1,
      needsManualTriage: false,
      aiOverridden: false,
      slaDueAt: hoursAhead(4),
      residentConfirmed: false,
      timeline: [
        { status: 'new', note: 'Resident reported high chlorine', by: 'System', at: hoursAgo(28) },
        { status: 'resolved', note: 'Vendor reported dilution complete', by: 'Pool Vendor', at: hoursAgo(12) },
        { status: 'reopened', note: 'Resident replied Not Resolved: "Water still cloudy and pungent smells remain"', by: 'Divya Nair', at: hoursAgo(2) },
      ],
      internalNotes: [
        { note: 'Pool closed until pH and chlorine test report reads under 1.5 ppm.', author: 'Vikram Malhotra', createdAt: hoursAgo(1.5) },
      ],
      createdAt: hoursAgo(28).toISOString(),
      updatedAt: hoursAgo(2).toISOString(),
    },
    {
      complaintId: 'SP-2026-0023',
      originalText: 'Someone constantly parking two bicycles right in front of fire exit door on 2nd floor.',
      translatedText: 'Someone constantly parking two bicycles right in front of fire exit door on 2nd floor.',
      language: 'en',
      summary: 'Bicycles blocking Wing C 2nd floor fire exit',
      category: 'parking',
      urgency: 'high',
      urgencyScore: 80,
      urgencyReason: 'Obstruction of designated fire escape route',
      isSafetyRisk: true,
      status: 'assigned',
      wing: 'C',
      flatNumber: 'C-201',
      commonArea: 'Wing C 2nd Floor Emergency Exit',
      residentName: 'Manoj Kumar',
      phone: '+91 98212 33333',
      assignedTo: 'Head Security Guard',
      duplicateOf: null,
      reportCount: 1,
      needsManualTriage: false,
      aiOverridden: false,
      slaDueAt: hoursAhead(3),
      timeline: [
        { status: 'new', note: 'Reported with photo', by: 'System', at: hoursAgo(5) },
        { status: 'assigned', note: 'Notice sticker placed on bicycles to move to bicycle stand immediately', by: 'Secretary', at: hoursAgo(2) },
      ],
      internalNotes: [],
      createdAt: hoursAgo(5).toISOString(),
      updatedAt: hoursAgo(2).toISOString(),
    },
    {
      complaintId: 'SP-2026-0024',
      originalText: 'Drainage cover near gate 3 is loose and rattles loudly every time a car drives over it.',
      translatedText: 'Drainage cover near gate 3 is loose and rattles loudly every time a car drives over it.',
      language: 'en',
      summary: 'Storm drain grill loose near Gate 3',
      category: 'other',
      urgency: 'low',
      urgencyScore: 34,
      urgencyReason: 'Rattling noise nuisance and potential tire pinch hazard',
      isSafetyRisk: false,
      status: 'resolved',
      wing: 'D',
      flatNumber: 'D-101',
      commonArea: 'Gate 3 Roadway',
      residentName: 'Suresh Menon',
      phone: '+91 98212 44444',
      assignedTo: 'Society Welder',
      duplicateOf: null,
      reportCount: 1,
      needsManualTriage: false,
      aiOverridden: false,
      slaDueAt: hoursAgo(15),
      resolvedAt: hoursAgo(12),
      residentConfirmed: true,
      timeline: [
        { status: 'new', note: 'Reported by D-101', by: 'System', at: hoursAgo(48) },
        { status: 'resolved', note: 'Heavy duty rubber lining inserted and frame welded', by: 'Welder', at: hoursAgo(12) },
      ],
      internalNotes: [],
      createdAt: hoursAgo(48).toISOString(),
      updatedAt: hoursAgo(12).toISOString(),
    },
    {
      complaintId: 'SP-2026-0025',
      originalText: 'Visitor vehicle parked in handicap slot near tower A entrance.',
      translatedText: 'Visitor vehicle parked in handicap slot near tower A entrance.',
      language: 'en',
      summary: 'Unauthorized car in accessible parking slot',
      category: 'parking',
      urgency: 'medium',
      urgencyScore: 64,
      urgencyReason: 'Blocks designated accessibility access for disabled residents',
      isSafetyRisk: false,
      status: 'resolved',
      wing: 'A',
      flatNumber: 'A-104',
      commonArea: 'Tower A Portico',
      residentName: 'Aarti Mathur',
      phone: '+91 98212 55555',
      assignedTo: 'Security Guard Gate 1',
      duplicateOf: null,
      reportCount: 1,
      needsManualTriage: false,
      aiOverridden: false,
      slaDueAt: hoursAgo(8),
      resolvedAt: hoursAgo(6),
      residentConfirmed: true,
      timeline: [
        { status: 'new', note: 'Logged by resident', by: 'System', at: hoursAgo(10) },
        { status: 'resolved', note: 'Security announced registration plate, visitor moved car to guest lot', by: 'Security Guard', at: hoursAgo(6) },
      ],
      internalNotes: [],
      createdAt: hoursAgo(10).toISOString(),
      updatedAt: hoursAgo(6).toISOString(),
    },
  ];

  // Daily digest sample
  const todayKey = now.toISOString().split('T')[0];
  const sampleDigest: IDigest = {
    date: todayKey,
    stats: {
      urgentCount: 3,
      newCount: 5,
      overdueCount: 2,
      mergedDuplicatesCount: 4,
      totalOpenCount: 14,
    },
    summaryHeadline:
      '3 urgent issues require attention today: Meter box electrical sparking in Wing B, total water outage in Wing A, and Lift C rapid door impact hazard.',
    rows: [
      {
        complaintId: 'SP-2026-0001',
        summary: 'Meter box sparking with burning smell',
        urgency: 'critical',
        category: 'electrical',
        flatNumber: 'B-101',
        wing: 'B',
        status: 'in_progress',
        isSafetyRisk: true,
        suggestedAction: 'Ensure electrician Santosh replaces fused breaker and tests load before 2 PM.',
      },
      {
        complaintId: 'SP-2026-0004',
        summary: 'Complete water outage in Wing A',
        urgency: 'critical',
        category: 'water',
        flatNumber: 'A-201',
        wing: 'A',
        status: 'in_progress',
        isSafetyRisk: true,
        suggestedAction: 'Confirm tanker arrival with Rajesh Nair and verify pump motor wiring.',
      },
      {
        complaintId: 'SP-2026-0012',
        summary: 'Wing C elevator door sensor closing aggressively',
        urgency: 'critical',
        category: 'lift',
        flatNumber: 'C-204',
        wing: 'C',
        status: 'in_progress',
        isSafetyRisk: true,
        suggestedAction: 'Follow up with Otis AMC engineer on optical curtain sensor realignment.',
      },
      {
        complaintId: 'SP-2026-0002',
        summary: 'Wing B passenger elevator out of service',
        urgency: 'high',
        category: 'lift',
        flatNumber: 'B-702',
        wing: 'B',
        status: 'assigned',
        isSafetyRisk: false,
        suggestedAction: '3 duplicate reports merged. Track Otis ticket #OTIS-4491.',
      },
      {
        complaintId: 'SP-2026-0014',
        summary: 'Turbid muddy water in Wing D taps',
        urgency: 'high',
        category: 'water',
        flatNumber: 'D-502',
        wing: 'D',
        status: 'new',
        isSafetyRisk: true,
        suggestedAction: 'Assign plumbing supervisor to check overhead tank sediment and flush lines.',
      },
      {
        complaintId: 'SP-2026-0022',
        summary: 'Excessive chemical chlorine dosage in pool',
        urgency: 'medium',
        category: 'other',
        flatNumber: 'A-402',
        wing: 'A',
        status: 'reopened',
        isSafetyRisk: true,
        suggestedAction: 'Complaint reopened by resident. Keep pool closed until water test passes.',
      },
    ],
    createdAt: now.toISOString(),
  };

  const sampleSettings = {
    slaHours: { critical: 2, high: 6, medium: 24, low: 72 },
    categories: ['water', 'lift', 'parking', 'noise', 'cleaning', 'electrical', 'security', 'other'],
    wings: ['A', 'B', 'C', 'D'],
    societyName: 'Greenwood Palms Co-op Housing Society',
    totalFlats: 120,
  };

  // Try MongoDB Atlas first
  const conn = await connectDB();
  if (conn) {
    console.log('Connecting to MongoDB Atlas to populate collections...');
    await UserModel.deleteMany({});
    await UserModel.insertMany(users);
    console.log(`✅ Seeded ${users.length} committee users in MongoDB`);

    await ComplaintModel.deleteMany({});
    await ComplaintModel.insertMany(sampleComplaints);
    console.log(`✅ Seeded ${sampleComplaints.length} complaints in MongoDB`);

    await DigestModel.deleteMany({});
    await DigestModel.create(sampleDigest);
    console.log('✅ Seeded Daily Digest in MongoDB');

    await SettingsModel.deleteMany({});
    await SettingsModel.create(sampleSettings);
    console.log('✅ Seeded Settings in MongoDB');
  }

  // Always also write to the local fallback store file for seamless local portability!
  const fallbackDir = path.join(process.cwd(), '.data');
  if (!fs.existsSync(fallbackDir)) {
    fs.mkdirSync(fallbackDir, { recursive: true });
  }
  const fallbackFile = path.join(fallbackDir, 'society_store.json');
  fs.writeFileSync(
    fallbackFile,
    JSON.stringify(
      {
        users,
        complaints: sampleComplaints,
        digests: [sampleDigest],
        settings: sampleSettings,
      },
      null,
      2
    ),
    'utf-8'
  );
  console.log(`✅ Local fallback store synchronized at: ${fallbackFile}`);
  console.log('🎉 Seed completed successfully!');
  console.log('\nDefault Committee Logins:');
  console.log('  👑 Admin:      admin@society.org     / admin123');
  console.log('  📋 Secretary:  secretary@society.org / member123');
  console.log('  💰 Treasurer:  treasurer@society.org / member123');
}

seed()
  .then(() => process.exit(0))
  .catch((err) => {
    console.error('❌ Seed error:', err);
    process.exit(1);
  });
